### ISSUE TITLE
[query transformation plugin] system not handling sessions

### ISSUE THREAD

**Issue by guidozuc** [ielab/searchrefiner#37]
The system is currently not handling session and killing abandoned queries.
Example:

- I issued a long query. After many minutes, I gave up
- I changed the relevant docs in the settings
- I issued a new, shorter query
- I interacted with the new query and kept refining
- at some point, the results for the first, long query arrived: the query got into the history of the current query. Had no relevant docs retrieved, because it used the qrels from the second query

**Comment by hscells** [comment]
I added a queue system so that each user can only have one query in the queue. The page will now redirect to a loading page while waiting in the queue.
